# Generated by Django 3.1.7 on 2021-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraut', '0004_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='title',
        ),
        migrations.AlterField(
            model_name='data',
            name='content',
            field=models.JSONField(),
        ),
    ]
