# Generated by Django 3.1.7 on 2021-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraut', '0005_auto_20210312_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='content',
            field=models.JSONField(null=True),
        ),
    ]
