# Generated by Django 3.1.7 on 2021-03-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraut', '0006_auto_20210312_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='password',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
