# Generated by Django 3.1.7 on 2021-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraut', '0008_auto_20210314_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='passwor',
            field=models.TextField(default=None),
        ),
    ]
