# Generated by Django 3.1.7 on 2021-03-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useraut', '0009_auto_20210314_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='passwor',
            new_name='code',
        ),
    ]
